# Generated by Django 3.1.1 on 2020-09-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkadventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('tour_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
