# Generated by Django 3.1.1 on 2020-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkadventure', '0004_auto_20200907_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TourBooking',
        ),
    ]
