# Generated by Django 3.1.1 on 2020-09-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkadventure', '0006_auto_20200907_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='popular',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
    ]
