# Generated by Django 3.1.1 on 2020-09-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkadventure', '0008_auto_20200908_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=20000)),
            ],
        ),
    ]
