# Generated by Django 3.1.1 on 2020-09-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkadventure', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_descr',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
