# Generated by Django 3.1.1 on 2020-09-12 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkadventure', '0011_auto_20200911_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_descr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
